optimizer:
  name: adam
  lr: 1.0e-3
  weight_decay: 0

train:
  epoch: 1000
  batch_size: 1024
  save_model: false
  loss: pairwise
  test_step: 3
  reproducible: true
  seed: 2024
  patience: 20

test:
  metrics: [recall, ndcg]
  k: [5, 10, 20]
  batch_size: 1024

data:
  type: general_cf
  name: yelp


model:
  name: mult_vae_cpdm
  # general parameters here

  # dataset-specific parameters here
  dropout: 0.2
  reg_weight: 1.0e-6
  # for amazon
  amazon:
    dropout: 0.3
    beta: 0.2
    reg_weight: 1.0e-6
  # for yelp
  yelp:
    dropout: 0.3
    beta: 0.9
    reg_weight: 1.0e-6
  # for steam
  steam:
    dropout: 0.2
    beta: 0.6
    reg_weight: 1.0e-6
